<a href="https://colab.research.google.com/github/Ghalia671/MODULE1/blob/master/Ghalia_2_0_validation_crois%C3%A9e.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revue de la problématique de sur apprentissage

In [1]:
import pandas as pd
import numpy as np

## Données

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target


In [3]:
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer()

X = cancer.data
y = cancer.target

## Algorithmes

In [4]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)

**Question** créer d'autres modèles et choisissez les hyperparamètres pour avoir le sur-apprentissage

In [7]:
from sklearn.svm import SVC
svm_lin = SVC(kernel = 'linear', random_state = 0,probability=True,C=0.3)

svm_lin.fit(X,y)
pred_svm = svm_lin.predict(X)
pred_svm

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

## Apprentissage des modèles

In [5]:
model.fit(X, y)
pred = model.predict(X)

## Performance

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y, pred)

1.0

# Split apprentissage/test

## Split avec fonction

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0,
                                  train_size=0.3)


## Split à la main

**Question** Pour vérifier la compréhension du split, implémenter une fonction à la main, avec `random.permutation` de `numpy`. 

In [27]:
matrix = np.random.permutation(10)
train_DB = np.random.choice(range(matrix.shape[0]), size=(8,), replace=False)    
test_DB = np.random.choice(range(matrix.shape[0]), size=(2,), replace=False)    
print(train_DB)
print(test_DB)


[3 7 1 8 9 2 6 0]
[6 7]


## Performance du test

In [28]:
model.fit(X_train, y_train)

pred_test = model.predict(X_test)

accuracy_score(y_test, pred_test)

0.9147869674185464

# Validation croisée

## Exemple simple

In [29]:
import numpy as np

from sklearn.model_selection import KFold

data = np.arange(1,10,1)

kfold = KFold(3, shuffle=True, random_state=1)

for train, test in kfold.split(data):
	print('train: %s, test: %s' % (data[train], data[test]))

train: [1 2 4 5 6 8], test: [3 7 9]
train: [3 4 5 6 7 9], test: [1 2 8]
train: [1 2 3 7 8 9], test: [4 5 6]


In [30]:
kfold = KFold(3, shuffle=False)

for train, test in kfold.split(data):
	print('train: %s, test: %s' % (data[train], data[test]))

train: [4 5 6 7 8 9], test: [1 2 3]
train: [1 2 3 7 8 9], test: [4 5 6]
train: [1 2 3 4 5 6], test: [7 8 9]


## Application à un modèle

In [31]:
from sklearn.model_selection import cross_val_score

scores=cross_val_score(model, X, y, cv=5)

scores

array([0.85964912, 0.92982456, 0.9122807 , 0.9122807 , 0.91150442])

In [32]:
model = KNeighborsClassifier(n_neighbors=2)
cross_val_score(model, X, y, cv=5)


array([0.89473684, 0.9122807 , 0.92982456, 0.89473684, 0.89380531])

In [33]:
scores.mean()

0.9051079024996118

## Plus d'informations

In [34]:
from sklearn.model_selection import cross_validate

res = cross_validate(model, X, y, cv=5,
                     return_train_score=True)
res

{'fit_time': array([0.0016818 , 0.00109291, 0.00111747, 0.00106978, 0.00107646]),
 'score_time': array([0.00630498, 0.00417805, 0.00427747, 0.00417161, 0.00408816]),
 'test_score': array([0.89473684, 0.9122807 , 0.92982456, 0.89473684, 0.89380531]),
 'train_score': array([0.96703297, 0.97142857, 0.96703297, 0.96703297, 0.97149123])}

In [35]:
res_df = pd.DataFrame(res)
display(res_df)
print("Mean times and scores:\n", res_df.mean())

fit_time  score_time  test_score  train_score
0  0.001682    0.006305    0.894737     0.967033
1  0.001093    0.004178    0.912281     0.971429
2  0.001117    0.004277    0.929825     0.967033
3  0.001070    0.004172    0.894737     0.967033
4  0.001076    0.004088    0.893805     0.971491

Mean times and scores:
 fit_time       0.001208
score_time     0.004604
test_score     0.905077
train_score    0.968804
dtype: float64


## `Suffle` de la fonction k fold

In [36]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)

In [37]:
cross_val_score(model, iris.data, iris.target, cv=kfold)

array([1.        , 1.        , 0.9       , 0.9       , 0.73333333])

In [38]:
kfold = KFold(n_splits=3)
cross_val_score(model, iris.data, iris.target, cv=kfold)

array([0., 0., 0.])

In [39]:
kfold = KFold(n_splits=3, shuffle=True, random_state=0)

cross_val_score(model, iris.data, iris.target, cv=kfold)

array([0.96, 0.92, 0.96])

# Validation croisée Stratifiée

## Principe

In [40]:
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target


In [41]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5)


In [42]:
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] TEST: [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]
TRAIN: [  0   1   2   3   4   5   6   7   8   9  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 120

## Application

**Question** implémenter la validation croisée avec `StratifiedKFold`, en utilisant les données `iris`.

In [44]:
cross_val_score(model, iris.data, iris.target, cv=skf)

array([0.96666667, 0.93333333, 0.93333333, 0.9       , 1.        ])

# Validation croisée Leave-one-out

LOOCV: Leave-one-out cross-validation

Equivalent à `KFold(n_splits=n)` où `n` est le nombre d'observations.

## Leave One Out

In [45]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

X = np.array([[1, 2,3], [4,5,6],[7,8,9]])
y = np.array([1,2,2])

loo = LeaveOneOut()
loo.get_n_splits(X)

for train_index, test_index in loo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    #print(X_train, X_test, y_train, y_test)

TRAIN: [1 2] TEST: [0]
TRAIN: [0 2] TEST: [1]
TRAIN: [0 1] TEST: [2]


In [46]:
loo.get_n_splits(X)

3

## Application

**Question** implémenter la méthode de validation croisée avec `LeaveOneOut`.

In [47]:

# application aux données iris ou breast cancer
cross_val_score(model, iris.data, iris.target, cv=loo)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
cross_val_score(model, cancer.data, cancer.target, cv=loo)

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

# Validation croisée avec sélections aléatoires

## Split aléatoire

In [49]:
from sklearn.model_selection import ShuffleSplit

shufflesplit=ShuffleSplit(test_size=.3, train_size=.5, n_splits=3)

data = np.arange(0,10,1)

for train, test in shufflesplit.split(data):
	print('train: %s, test: %s' % (data[train], data[test]))
 

train: [8 7 3 0 6], test: [5 2 1]
train: [7 9 5 3 4], test: [8 0 6]
train: [9 8 1 4 0], test: [3 5 7]


Appication à iris

In [50]:
from sklearn.model_selection import ShuffleSplit

shuffle_split = ShuffleSplit(test_size=.5, train_size=.5, n_splits=10)

scores = cross_val_score(model, iris.data, iris.target, cv=shuffle_split)

print("Cross-validation scores:\n{}".format(scores))

Cross-validation scores:
[0.88       0.94666667 0.94666667 0.94666667 0.94666667 0.94666667
 0.96       0.94666667 0.92       0.96      ]


## Split stratifié

**Question** application du split stratifié pour les données `iris`.

In [51]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=100, test_size=0.2)

# code 

scs = cross_val_score(model, iris.data, iris.target, cv=split)

print("Cross-validation scores:\n{}".format(scs))

Cross-validation scores:
[0.93333333 0.96666667 0.93333333 0.86666667 0.9        0.96666667
 0.93333333 0.93333333 0.93333333 0.96666667 0.96666667 0.96666667
 0.93333333 1.         0.93333333 0.93333333 1.         0.93333333
 1.         0.96666667 0.96666667 0.9        0.96666667 0.9
 0.9        0.9        0.93333333 0.93333333 0.93333333 0.96666667
 0.96666667 0.86666667 1.         0.93333333 0.96666667 0.96666667
 0.93333333 0.96666667 0.96666667 0.93333333 0.96666667 0.96666667
 0.9        0.96666667 0.93333333 1.         0.96666667 0.93333333
 0.96666667 0.86666667 0.93333333 0.96666667 0.96666667 0.93333333
 0.93333333 1.         0.93333333 0.96666667 0.9        0.86666667
 0.96666667 0.96666667 0.86666667 0.93333333 1.         1.
 0.93333333 0.9        0.96666667 0.96666667 0.96666667 0.96666667
 0.96666667 0.93333333 1.         0.9        0.9        0.93333333
 0.93333333 0.96666667 0.93333333 0.93333333 0.96666667 0.9
 0.96666667 1.         0.9        1.         0.96666667 1.
