<a href="https://colab.research.google.com/github/Ghalia671/MODULE1/blob/master/Ghalia_2_2_m%C3%A9triques_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Apprentissage/test

In [1]:
import matplotlib.pyplot as plt
from sklearn import datasets

from sklearn import metrics

cancer = datasets.load_breast_cancer()
X = cancer.data
y = cancer.target


In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train.shape, X_test.shape)

(398, 30) (171, 30)


In [3]:
from sklearn import linear_model

clf = linear_model.LogisticRegression(max_iter=5000)
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=5000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [4]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,clf.predict(X_test))

0.9766081871345029

## Matrice de confusion

In [5]:
cm=metrics.confusion_matrix(y_test,clf.predict(X_test))

In [6]:
cm

array([[ 61,   2],
       [  2, 106]])

In [7]:
tn, fp, fn, tp = cm.ravel()

**Question** Calculer la précision, rappel, le taux de faux positif, le taux de vrai positif, ainsi que le score F1.

In [9]:
accuracy = 1 - ((2+2)/(61+2+2+106))
print("accuracy : ",round(accuracy * 100,2)," %")

precision = 106/(106+2)
print("precision : ",round(precision * 100,2)," %")

rappel = 2 / (61+2)
print("rappel : ",round(rappel * 100,2)," %")

score_F1 = 2 * ((precision * rappel)/(precision + rappel))
print("score F1 : ",round(score_F1 * 100,2)," %")

accuracy :  97.66  %
precision :  98.15  %
rappel :  3.17  %
score F1 :  6.15  %


## Rapport des résultats de prédiction

On peut utiliser la fonction `classification_report` pour avoir un ensemble de résultats.

In [10]:
from sklearn.metrics import classification_report

print(classification_report(y_test,clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        63
           1       0.98      0.98      0.98       108

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171



# Validation croisée

## Justesse

In [11]:
from sklearn.model_selection import cross_val_score

cross_val_score(clf, X, y, scoring='accuracy')

array([0.93859649, 0.94736842, 0.98245614, 0.92982456, 0.96460177])

## Score F1

In [12]:
cross_val_score(clf, X, y, scoring='f1')

array([0.95302013, 0.95833333, 0.98611111, 0.94444444, 0.97142857])

## ROC AUC

In [13]:
cross_val_score(clf, X, y, scoring='roc_auc')

array([0.99410416, 0.99344907, 0.99801587, 0.97949735, 0.99765258])

# Validation croisée stratifiée

**Question** Utiliser la validation croisée stratifiée

In [14]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5)
cross_val_score(clf, X, y, cv=skf)

array([0.93859649, 0.94736842, 0.98245614, 0.92982456, 0.96460177])

# Classification multiclasse

On peut prendre l'exemple des données `iris` pour lesquelles on a trois classes (trois espèces d'iris).



In [15]:
# Importer les données
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

## Calculs de métriques

**Question** appliquer les différentes métriques comme `accuracy`, `precision`, `recall`.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
from sklearn import linear_model

clf = linear_model.LogisticRegression(max_iter=5000)
clf.fit(X_train,y_train)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,clf.predict(X_test))

In [18]:
cm=metrics.confusion_matrix(y_test,clf.predict(X_test))
cm

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y_test,clf.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



## Méthodes de calculs de moyenne

Pour le score F1, on doit préciser `f1_micro` ou `f1_macro`.

In [20]:
cross_val_score(clf, X, y, scoring='f1_micro')

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

**Explication des moyennes micro, macro**

Le score F1 se calcule à partir du couple précision et rappel. Les calculs de moyennes micro ou macro portent sur les moyenens de précision et de rappel.

Prenons l'exemple de calcul de précision, pour trois classes suivantes:

- Classe 1: 1 Vrai Positif (VP) et 1 Faux Positif (FP)
- Classe 2: 20 VP et 80 FP
- Classe 3: 1 VP et 1 FP



On peut calculer la précision pour les trois classes: 

- Classe 1: précision $Pr_1 = 0.5$
- Classe 2: précision $Pr_2 = 0.2$
- Classe 3: précision $Pr_3 = 0.5$

La moyenne macro se calcule de la manière suivante:

$$Pr_{macro}=\frac{Pr_1+Pr_2+Pr_3}{3}=\frac{0.5+0.2+0.5}{3}=0.4$$

La moyenne micro se calcule de la manière suivante: 

$$Pr_{micro}=\frac{1+20+1}{2+100+2}=0.21$$