<a href="https://colab.research.google.com/github/Ghalia671/MODULE1/blob/master/Ghalia_Variables_cat%C3%A9goriques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Variables catégoriques nominales


## Transformation label binaire

In [1]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

feature = np.array([
    ["Paris"],
    ["Courbevoie"],
    ["Paris"],
    ["Puteaux"],
    ["Paris"]
])

labelbi = LabelBinarizer()

labelbi.fit_transform(feature)

array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [2]:
labelbi.classes_

array(['Courbevoie', 'Paris', 'Puteaux'], dtype='<U10')

In [3]:
labelbi.inverse_transform(labelbi.transform(feature))

array(['Paris', 'Courbevoie', 'Paris', 'Puteaux', 'Paris'], dtype='<U10')

**Question** transformer le vecteur suivant en un vecteur binaire.

In [4]:
target = np.array([
    ["oui"],
    ["oui"],
    ["non"],
    ["non"],
    ["oui"]
])

In [5]:

labelbi1 = LabelBinarizer()

labelbi1.fit_transform(target)

array([[1],
       [1],
       [0],
       [0],
       [1]])

## Transformation multilabel

In [6]:

multiclass_feature = [
    ("Paris", "75"),
    ("Courbevoie", "92"),
    ("Paris", "75"),
    ("Puteaux", "92"),
    ("Paris", "75")
]


label_multiclass = MultiLabelBinarizer()

label_multiclass.fit_transform(multiclass_feature)

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0]])

In [7]:
label_multiclass.classes_

array(['75', '92', 'Courbevoie', 'Paris', 'Puteaux'], dtype=object)

## Encodeur OneHot

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
onehotenc = OneHotEncoder(handle_unknown='ignore')

onehotenc.fit(multiclass_feature)

onehotenc.categories_


[array(['Courbevoie', 'Paris', 'Puteaux'], dtype=object),
 array(['75', '92'], dtype=object)]

In [10]:
onehotenc.transform(multiclass_feature).toarray()

array([[0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

## Dummy variables

Fonction équivalent avec `pandas`

In [11]:
import pandas as pd

pd.get_dummies(feature[:, 0])

Courbevoie  Paris  Puteaux
0           0      1        0
1           1      0        0
2           0      1        0
3           0      0        1
4           0      1        0

In [12]:

pd.get_dummies(feature[:, 0], drop_first=True)


Paris  Puteaux
0      1        0
1      0        0
2      1        0
3      0        1
4      1        0



# Variables catégoriques ordinales

In [13]:

import pandas as pd

# exemple de données
df = pd.DataFrame({"Satisfaction": ["Pas satisfait", "Pas satisfait", "Satisfait", "Très satisfait", "Très satisfait"]})

# créer un dictionnaire de mapping

scale_mapper = {
    "Pas satisfait": 1,
    "Satisfait": 2,
    "Très satisfait": 3
}

# remplacement de valeurs
df["Satisfaction"].replace(scale_mapper)

0    1
1    1
2    2
3    3
4    3
Name: Satisfaction, dtype: int64

On peut aussi utiliser `OrdinalEncoder`

In [14]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[["Pas satisfait", "Satisfait", "Très satisfait"]])
encoder.fit_transform(df[["Satisfaction"]])


array([[0.],
       [0.],
       [1.],
       [2.],
       [2.]])

# Gestion des données manquantes

In [15]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

X = np.array([[0, 2.10, 1.45],
            [1, 1.18, 1.33],
            [0, 1.22, 1.27],
            [0, 2.2, 0.67],
            [1, -0.21, -1.19]])

X_with_nan = np.array([[np.nan, 0.87, 1.31],
                      [np.nan, -0.67, -0.22]])

# entrainer le modèle de knn
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X[:,1:], X[:, 0])

# prédire les valeurs manquantes
imputed_values = trained_model.predict(X_with_nan[:, 1:])

# concaténation
X_with_imputed = np.hstack((imputed_values.reshape(-1, 1), X_with_nan[:, 1:]))


In [16]:
X_with_imputed

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22]])

In [17]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent')

imputer.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [18]:
imputer.transform(X_with_nan)

array([[ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22]])

# Exercice

**Question** transformer les variables catégoriques dans la base de données `insurance` importée dans la cellule suivante.

In [19]:
import pandas as pd
url = 'http://dataks.bitbucket.io/ml/insurance.csv'
data = pd.read_csv(url)

In [20]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
data.info()

In [23]:
label_multiclass1 = MultiLabelBinarizer()

label_multiclass1.fit_transform(data[["sex","smoker","region"]])

array([[1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 0, 0]])

Documentation

- https://inmachineswetrust.com/posts/drop-first-columns/
